package com.thalesgroup.rtti._2017_10_01.ldbsv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-05-24T15:42:24.274+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", name = "LDBSVServiceSoap")
@XmlSeeAlso({com.thalesgroup.rtti._2014_02_20.ldbsv.types.ObjectFactory.class, com.thalesgroup.rtti._2015_11_27.ldbsv.types.ObjectFactory.class, com.thalesgroup.rtti._2016_02_16.ldbsv.types.ObjectFactory.class, com.thalesgroup.rtti._2017_10_01.ldbsv.types.ObjectFactory.class, com.thalesgroup.rtti._2007_10_10.ldb.commontypes.ObjectFactory.class, com.thalesgroup.rtti._2012_01_13.ldbsv.types.ObjectFactory.class, com.thalesgroup.rtti._2015_05_14.ldbsv_ref.ObjectFactory.class, com.thalesgroup.rtti._2015_11_27.ldbsv.commontypes.ObjectFactory.class, ObjectFactory.class, com.thalesgroup.rtti._2013_11_28.token.types.ObjectFactory.class, com.thalesgroup.rtti._2017_10_01.ldbsv.commontypes.ObjectFactory.class, com.thalesgroup.rtti._2015_05_14.ldbsv_ref.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LDBSVServiceSoap {

    @WebMethod(operationName = "GetNextDeparturesWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetNextDeparturesWithDetails")
    @WebResult(name = "GetNextDeparturesWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public DeparturesBoardWithDetailsResponseType getNextDeparturesWithDetails(

        @WebParam(partName = "parameters", name = "GetNextDeparturesWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetDeparturesParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalDepartureBoardByCRS", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetArrivalDepartureBoardByCRS")
    @WebResult(name = "GetArrivalDepartureBoardByCRSResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getArrivalDepartureBoardByCRS(

        @WebParam(partName = "parameters", name = "GetArrivalDepartureBoardByCRSRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetHistoricDepartureBoard", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetHistoricDepartureBoard")
    @WebResult(name = "GetHistoricDepartureBoardResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetHistoricDepartureBoardResponseType getHistoricDepartureBoard(

        @WebParam(partName = "parameters", name = "GetHistoricDepartureBoardRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetHistoricDepartureBoardRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetDepartureBoardByTIPLOC", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetDepartureBoardByTIPLOC")
    @WebResult(name = "GetDepartureBoardByTIPLOCResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getDepartureBoardByTIPLOC(

        @WebParam(partName = "parameters", name = "GetDepartureBoardByTIPLOCRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByTIPLOCParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetServiceDetailsByRID", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetServiceDetailsByRID")
    @WebResult(name = "GetServiceDetailsByRIDResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetServiceDetailsResponseType getServiceDetailsByRID(

        @WebParam(partName = "parameters", name = "GetServiceDetailsByRIDRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetServiceDetailsByRIDParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetReasonCode", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetReasonCode")
    @WebResult(name = "GetReasonCodeResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetReasonCodeResponseType getReasonCode(

        @WebParam(partName = "parameters", name = "GetReasonCodeRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetReasonCodeRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetHistoricServiceDetails", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetHistoricServiceDetails")
    @WebResult(name = "GetHistoricServiceDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetHistoricServiceDetailsResponseType getHistoricServiceDetails(

        @WebParam(partName = "parameters", name = "GetHistoricServiceDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetHistoricServiceDetailsRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetNextDepartures", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetNextDepartures")
    @WebResult(name = "GetNextDeparturesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public DeparturesBoardResponseType getNextDepartures(

        @WebParam(partName = "parameters", name = "GetNextDeparturesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetDeparturesParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetDepartureBoardByCRS", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetDepartureBoardByCRS")
    @WebResult(name = "GetDepartureBoardByCRSResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getDepartureBoardByCRS(

        @WebParam(partName = "parameters", name = "GetDepartureBoardByCRSRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetArrBoardWithDetails")
    @WebResult(name = "GetArrBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetStationBoardWithDetailsResponseType getArrBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetArrBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalBoardByCRS", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetArrivalBoardByCRS")
    @WebResult(name = "GetArrivalBoardByCRSResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getArrivalBoardByCRS(

        @WebParam(partName = "parameters", name = "GetArrivalBoardByCRSRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetHistoricTimeLine", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetHistoricTimeLine")
    @WebResult(name = "GetHistoricTimeLineResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetHistoricTimeLineResponseType getHistoricTimeLine(

        @WebParam(partName = "parameters", name = "GetHistoricTimeLineRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetHistoricTimeLineRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetReasonCodeList", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetReasonCodeList")
    @WebResult(name = "GetReasonCodeListResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetReasonCodeListResponseType getReasonCodeList(

        @WebParam(partName = "parameters", name = "GetReasonCodeListRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        VoidParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetDisruptionList", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetDisruptionList")
    @WebResult(name = "GetDisruptionListResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetDisruptionListResponseType getDisruptionList(

        @WebParam(partName = "parameters", name = "GetDisruptionListRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetDisruptionListRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetFastestDepartures", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetFastestDepartures")
    @WebResult(name = "GetFastestDeparturesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public DeparturesBoardResponseType getFastestDepartures(

        @WebParam(partName = "parameters", name = "GetFastestDeparturesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetDeparturesParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetFastestDeparturesWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetFastestDeparturesWithDetails")
    @WebResult(name = "GetFastestDeparturesWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public DeparturesBoardWithDetailsResponseType getFastestDeparturesWithDetails(

        @WebParam(partName = "parameters", name = "GetFastestDeparturesWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetDeparturesParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetSourceInstanceNames", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetSourceInstanceNames")
    @WebResult(name = "GetSourceInstanceNamesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetSourceInstanceNamesResponseType getSourceInstanceNames(

        @WebParam(partName = "parameters", name = "GetSourceInstanceNamesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        VoidParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrDepBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetArrDepBoardWithDetails")
    @WebResult(name = "GetArrDepBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetStationBoardWithDetailsResponseType getArrDepBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetArrDepBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalDepartureBoardByTIPLOC", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetArrivalDepartureBoardByTIPLOC")
    @WebResult(name = "GetArrivalDepartureBoardByTIPLOCResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getArrivalDepartureBoardByTIPLOC(

        @WebParam(partName = "parameters", name = "GetArrivalDepartureBoardByTIPLOCRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByTIPLOCParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetArrivalBoardByTIPLOC", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/GetArrivalBoardByTIPLOC")
    @WebResult(name = "GetArrivalBoardByTIPLOCResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetBoardResponseType getArrivalBoardByTIPLOC(

        @WebParam(partName = "parameters", name = "GetArrivalBoardByTIPLOCRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByTIPLOCParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "QueryServices", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/QueryServices")
    @WebResult(name = "QueryServicesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public QueryServicesResponseType queryServices(

        @WebParam(partName = "parameters", name = "QueryServicesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        QueryServicesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "QueryHistoricServices", action = "http://thalesgroup.com/RTTI/2012-01-13/ldbsv/QueryHistoricServices")
    @WebResult(name = "QueryHistoricServicesResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public QueryHistoricServicesResponseType queryHistoricServices(

        @WebParam(partName = "parameters", name = "QueryHistoricServicesRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        QueryHistoricServicesRequestParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );

    @WebMethod(operationName = "GetDepBoardWithDetails", action = "http://thalesgroup.com/RTTI/2015-05-14/ldbsv/GetDepBoardWithDetails")
    @WebResult(name = "GetDepBoardWithDetailsResponse", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/", partName = "parameters")
    public GetStationBoardWithDetailsResponseType getDepBoardWithDetails(

        @WebParam(partName = "parameters", name = "GetDepBoardWithDetailsRequest", targetNamespace = "http://thalesgroup.com/RTTI/2017-10-01/ldbsv/")
        GetBoardByCRSParams parameters,
        @WebParam(partName = "AccessToken", name = "AccessToken", targetNamespace = "http://thalesgroup.com/RTTI/2013-11-28/Token/types", header = true)
        com.thalesgroup.rtti._2013_11_28.token.types.AccessToken accessToken
    );
}
